name: Flutter CI/CD with Firebase App Distribution

on:
  push:
    branches:
      - main  # change if needed

jobs:
  distribute:
    runs-on: macos-latest  # needed for iOS builds

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      # 3. Restore Firebase config files from secrets
      - name: Decode google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > android/app/google-services.json

    #   - name: Decode GoogleService-Info.plist
    #     run: echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" | base64 --decode > ios/Runner/GoogleService-Info.plist

      # 4. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5. Build Android APK
      - name: Build Android release APK
        run: flutter build apk --release

      # 6. Build iOS IPA (requires signing setup in real project)
    #   - name: Build iOS release IPA
    #     run: flutter build ios --release --no-codesign

      # 7. Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 8. Distribute Android to Firebase
      - name: Distribute Android APK
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID_ANDROID }} \
            --groups "qa-team" \
            --release-notes "Automated Android build from GitHub Actions"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      # 9. Distribute iOS to Firebase
    #   - name: Distribute iOS IPA
    #     run: |
    #       firebase appdistribution:distribute build/ios/iphoneos/Runner.app \
    #         --app ${{ secrets.FIREBASE_APP_ID_IOS }} \
    #         --groups "qa-team" \
    #         --release-notes "Automated iOS build from GitHub Actions"
    #     env:
    #       FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
